image: node:24

variables:
  TZ: Asia/Jakarta

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - npm ci
    - npm run mode:prod
    - npx astro build
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment: production
