export interface Deal {
  slug: string;
  title: string;
  description: string;
  price: number;
  originalPrice?: number;
  discount?: number;
  category: string;
  subcategory?: string;
  provider: string;
  image: string;
  url: string;
  coupon?: string;
  rating?: number;
  students?: number;
  instructor?: string;
  duration?: string;
  contentNotes?: string;
  level?: string;
  language?: string;
  learn?: string[];
  requirements?: string[];
  skills?: string[];
  tags?: string[];
  seoTitle?: string;
  seoDescription?: string;
  seoOgImage?: string;
  expiresAt?: string;
  createdAt?: string;
  updatedAt?: string;
  faqs?: { q: string; a: string }[];
  priceHistory?: { price: number; checkedAt: string }[];
}
